// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/employe_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 8563377791112157248),
      name: 'EmployeeDetails',
      lastPropertyId: const obx_int.IdUid(16, 8550115732522719415),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8376471784669803994),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5846812338700248403),
            name: 'sId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7130249209748264536),
            name: 'bloodGroup',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1625125863153439836),
            name: 'createdBy',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7347210135673340645),
            name: 'createdOn',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8664775725037658997),
            name: 'dob',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 6974264154339196100),
            name: 'employmentType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 4575126159877187229),
            name: 'hierarchyId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2790910235518687694),
            name: 'mobileNo',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 5716250100119281231),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 2535568746378465553),
            name: 'status',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 3259929908702361440),
            name: 'supervisorId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 6436475039788204726),
            name: 'tradeType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 5398499484375253587),
            name: 'labourId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 1477850734358336002)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 1004457080500487001),
            name: 'faceEmbedding',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 8550115732522719415),
            name: 'createdDate',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 8563377791112157248),
      lastIndexId: const obx_int.IdUid(1, 1477850734358336002),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    EmployeeDetails: obx_int.EntityDefinition<EmployeeDetails>(
        model: _entities[0],
        toOneRelations: (EmployeeDetails object) => [],
        toManyRelations: (EmployeeDetails object) => {},
        getId: (EmployeeDetails object) => object.id,
        setId: (EmployeeDetails object, int id) {
          object.id = id;
        },
        objectToFB: (EmployeeDetails object, fb.Builder fbb) {
          final sIdOffset =
              object.sId == null ? null : fbb.writeString(object.sId!);
          final bloodGroupOffset = object.bloodGroup == null
              ? null
              : fbb.writeString(object.bloodGroup!);
          final createdByOffset = object.createdBy == null
              ? null
              : fbb.writeString(object.createdBy!);
          final createdOnOffset = object.createdOn == null
              ? null
              : fbb.writeString(object.createdOn!);
          final dobOffset =
              object.dob == null ? null : fbb.writeString(object.dob!);
          final employmentTypeOffset = object.employmentType == null
              ? null
              : fbb.writeString(object.employmentType!);
          final hierarchyIdOffset = object.hierarchyId == null
              ? null
              : fbb.writeString(object.hierarchyId!);
          final mobileNoOffset = object.mobileNo == null
              ? null
              : fbb.writeString(object.mobileNo!);
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final statusOffset =
              object.status == null ? null : fbb.writeString(object.status!);
          final supervisorIdOffset = object.supervisorId == null
              ? null
              : fbb.writeString(object.supervisorId!);
          final tradeTypeOffset = object.tradeType == null
              ? null
              : fbb.writeString(object.tradeType!);
          final labourIdOffset = object.labourId == null
              ? null
              : fbb.writeString(object.labourId!);
          final faceEmbeddingOffset = object.faceEmbedding == null
              ? null
              : fbb.writeString(object.faceEmbedding!);
          fbb.startTable(17);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, sIdOffset);
          fbb.addOffset(2, bloodGroupOffset);
          fbb.addOffset(3, createdByOffset);
          fbb.addOffset(4, createdOnOffset);
          fbb.addOffset(5, dobOffset);
          fbb.addOffset(6, employmentTypeOffset);
          fbb.addOffset(7, hierarchyIdOffset);
          fbb.addOffset(8, mobileNoOffset);
          fbb.addOffset(9, nameOffset);
          fbb.addOffset(10, statusOffset);
          fbb.addOffset(11, supervisorIdOffset);
          fbb.addOffset(12, tradeTypeOffset);
          fbb.addOffset(13, labourIdOffset);
          fbb.addOffset(14, faceEmbeddingOffset);
          fbb.addInt64(15, object.createdDate?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 34);
          final sIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final faceEmbeddingParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 32);
          final labourIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 30);
          final createdDateParam = createdDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createdDateValue);
          final bloodGroupParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final createdByParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final createdOnParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final dobParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final employmentTypeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16);
          final hierarchyIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18);
          final mobileNoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 22);
          final statusParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 24);
          final supervisorIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 26);
          final tradeTypeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 28);
          final object = EmployeeDetails(
              sId: sIdParam,
              faceEmbedding: faceEmbeddingParam,
              labourId: labourIdParam,
              createdDate: createdDateParam,
              bloodGroup: bloodGroupParam,
              createdBy: createdByParam,
              createdOn: createdOnParam,
              dob: dobParam,
              employmentType: employmentTypeParam,
              hierarchyId: hierarchyIdParam,
              mobileNo: mobileNoParam,
              name: nameParam,
              status: statusParam,
              supervisorId: supervisorIdParam,
              tradeType: tradeTypeParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [EmployeeDetails] entity fields to define ObjectBox queries.
class EmployeeDetails_ {
  /// see [EmployeeDetails.id]
  static final id =
      obx.QueryIntegerProperty<EmployeeDetails>(_entities[0].properties[0]);

  /// see [EmployeeDetails.sId]
  static final sId =
      obx.QueryStringProperty<EmployeeDetails>(_entities[0].properties[1]);

  /// see [EmployeeDetails.bloodGroup]
  static final bloodGroup =
      obx.QueryStringProperty<EmployeeDetails>(_entities[0].properties[2]);

  /// see [EmployeeDetails.createdBy]
  static final createdBy =
      obx.QueryStringProperty<EmployeeDetails>(_entities[0].properties[3]);

  /// see [EmployeeDetails.createdOn]
  static final createdOn =
      obx.QueryStringProperty<EmployeeDetails>(_entities[0].properties[4]);

  /// see [EmployeeDetails.dob]
  static final dob =
      obx.QueryStringProperty<EmployeeDetails>(_entities[0].properties[5]);

  /// see [EmployeeDetails.employmentType]
  static final employmentType =
      obx.QueryStringProperty<EmployeeDetails>(_entities[0].properties[6]);

  /// see [EmployeeDetails.hierarchyId]
  static final hierarchyId =
      obx.QueryStringProperty<EmployeeDetails>(_entities[0].properties[7]);

  /// see [EmployeeDetails.mobileNo]
  static final mobileNo =
      obx.QueryStringProperty<EmployeeDetails>(_entities[0].properties[8]);

  /// see [EmployeeDetails.name]
  static final name =
      obx.QueryStringProperty<EmployeeDetails>(_entities[0].properties[9]);

  /// see [EmployeeDetails.status]
  static final status =
      obx.QueryStringProperty<EmployeeDetails>(_entities[0].properties[10]);

  /// see [EmployeeDetails.supervisorId]
  static final supervisorId =
      obx.QueryStringProperty<EmployeeDetails>(_entities[0].properties[11]);

  /// see [EmployeeDetails.tradeType]
  static final tradeType =
      obx.QueryStringProperty<EmployeeDetails>(_entities[0].properties[12]);

  /// see [EmployeeDetails.labourId]
  static final labourId =
      obx.QueryStringProperty<EmployeeDetails>(_entities[0].properties[13]);

  /// see [EmployeeDetails.faceEmbedding]
  static final faceEmbedding =
      obx.QueryStringProperty<EmployeeDetails>(_entities[0].properties[14]);

  /// see [EmployeeDetails.createdDate]
  static final createdDate =
      obx.QueryDateProperty<EmployeeDetails>(_entities[0].properties[15]);
}
